# Generated by Django 5.1 on 2026-07-26
# ruff: noqa: E501

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("projects", "0003_executioncontract")]

    operations = [
        migrations.AddField(
            model_name="executioncontract",
            name="closure_state",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="executioncontract",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="executioncontract",
            name="consumed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="executioncontract",
            name="final_commit_sha",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="executioncontract",
            name="superseded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="supersedes",
                to="projects.executioncontract",
            ),
        ),
    ]
