# Generated by Django 5.2 on 2026-07-26

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("projects", "0005_governed_mcp_records")]

    operations = [
        migrations.CreateModel(
            name="ExecutionRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("repository", models.CharField(max_length=255)),
                ("branch", models.CharField(max_length=255)),
                ("baseline_commit", models.CharField(max_length=64)),
                ("contract_hash", models.CharField(max_length=64)),
                ("workspace_identifier", models.CharField(max_length=255)),
                ("provider_name", models.CharField(max_length=64)),
                ("provider_execution_id", models.CharField(blank=True, max_length=255)),
                (
                    "lifecycle",
                    models.CharField(
                        choices=[
                            ("REQUESTED", "Requested"),
                            ("STARTING", "Starting"),
                            ("RUNNING", "Running"),
                            ("VALIDATING", "Validating"),
                            ("REPAIRING", "Repairing"),
                            ("DOCUMENTING", "Documenting"),
                            ("CLOSING", "Closing"),
                            ("COMPLETED", "Completed"),
                            ("BLOCKED_BUSINESS_DECISION", "Blocked business"),
                            ("BLOCKED_EXTERNAL_INPUT", "Blocked external"),
                            ("FAILED_GOVERNANCE", "Failed governance"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="REQUESTED",
                        max_length=32,
                    ),
                ),
                ("current_phase", models.CharField(default="PREFLIGHT", max_length=64)),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("gate_rerun_count", models.PositiveIntegerField(default=0)),
                ("current_blocker", models.JSONField(blank=True, default=dict)),
                ("final_commit_sha", models.CharField(blank=True, max_length=64)),
                ("terminal_state", models.CharField(blank=True, max_length=128)),
                ("evidence_root", models.CharField(max_length=255)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "audit_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="projects.mcpauditevent",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="projects.executioncontract",
                    ),
                ),
                (
                    "start_request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="run",
                        to="projects.executionstartrequest",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="ExecutionProgressEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.PositiveIntegerField()),
                ("event_type", models.CharField(max_length=64)),
                ("details", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="projects.executionrun",
                    ),
                ),
            ],
            options={"ordering": ["sequence"]},
        ),
        migrations.AddConstraint(
            model_name="executionprogressevent",
            constraint=models.UniqueConstraint(
                fields=("run", "sequence"), name="unique_execution_event_sequence"
            ),
        ),
    ]
