# Generated by Django 5.2.14 on 2026-07-27 08:25

from typing import Any

import django.db.models.deletion
from django.db import migrations, models


def establish_codex_openai_relationship(apps: Any, schema_editor: Any) -> None:
    Provider = apps.get_model("projects", "ExecutionProvider")
    try:
        openai = Provider.objects.get(provider_id="openai")
    except Provider.DoesNotExist:
        return
    Provider.objects.filter(provider_id="codex-cli").update(
        related_provider=openai,
        authentication_mode="CODEX_CLI_LOGIN",
        credential_binding="",
    )


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0013_openai_credential_binding"),
    ]

    operations = [
        migrations.AddField(
            model_name="executionprovider",
            name="authentication_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("OPENAI_API_CONNECTION", "OpenAI API connection"),
                    ("CODEX_CLI_LOGIN", "Codex CLI login"),
                    ("INHERITED_RUNTIME_CREDENTIAL", "Inherited runtime credential"),
                    ("OTHER_PROVEN_MODE", "Other proven mode"),
                ],
                help_text=(
                    "Proven authentication mode only; no credential values are stored."
                ),
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="executionprovider",
            name="related_provider",
            field=models.ForeignKey(
                blank=True,
                help_text=(
                    "Non-secret provider dependency; it never copies credentials."
                ),
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dependent_providers",
                to="projects.executionprovider",
            ),
        ),
        migrations.RunPython(
            establish_codex_openai_relationship,
            migrations.RunPython.noop,
        ),
    ]
