# Generated by Django 5.2.16 on 2026-07-28 13:33

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0016_project_repository_root"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrchestrationSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("idempotency_key", models.CharField(max_length=128, unique=True)),
                ("provider_id", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("request_summary", models.CharField(max_length=500)),
                ("correlation_id", models.CharField(max_length=128)),
                ("version", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orchestrations",
                        to="projects.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrchestrationDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("schema_version", models.CharField(max_length=16)),
                ("authority_classification", models.CharField(max_length=16)),
                ("policy_decision", models.CharField(max_length=32)),
                ("recommended_action", models.CharField(max_length=64)),
                ("rationale", models.CharField(max_length=1000)),
                ("evidence_references", models.JSONField(default=list)),
                ("risk_flags", models.JSONField(default=list)),
                ("policy_rule_ids", models.JSONField(default=list)),
                (
                    "product_owner_question",
                    models.CharField(blank=True, max_length=500),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decision",
                        to="projects.orchestrationsession",
                    ),
                ),
            ],
        ),
    ]
