# Generated by Django 5.2.16 on 2026-07-28 13:51

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0017_orchestrator_foundation"),
    ]

    operations = [
        migrations.CreateModel(
            name="FailureIncident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("idempotency_key", models.CharField(max_length=128, unique=True)),
                ("correlation_id", models.CharField(max_length=128)),
                ("summary", models.CharField(max_length=1000)),
                ("causal_classification", models.CharField(blank=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("ASSESSED", "Assessed"),
                            ("CLOSED", "Closed"),
                        ],
                        default="OPEN",
                        max_length=16,
                    ),
                ),
                ("timeline", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="failure_incidents",
                        to="projects.project",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incidents",
                        to="projects.orchestrationsession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OwnershipAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("selected_component", models.CharField(blank=True, max_length=255)),
                ("confidence", models.FloatField(default=0)),
                ("policy_decision", models.CharField(max_length=32)),
                ("reason", models.CharField(max_length=1000)),
                ("candidates", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "incident",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ownership_assessment",
                        to="projects.failureincident",
                    ),
                ),
                (
                    "selected_project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_incidents",
                        to="projects.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IncidentEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(max_length=255)),
                ("kind", models.CharField(max_length=64)),
                ("summary", models.CharField(max_length=1000)),
                ("provenance", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence",
                        to="projects.failureincident",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("incident", "reference"),
                        name="unique_incident_evidence_reference",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RepositoryDependency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("component_mapping", models.JSONField(default=dict)),
                ("autonomous_remediation_approved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "depends_on",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incoming_dependencies",
                        to="projects.project",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outgoing_dependencies",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "depends_on"),
                        name="unique_repository_dependency",
                    )
                ],
            },
        ),
    ]
