# Generated by Django 5.2.16 on 2026-07-28

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "projects",
            "0018_failureincident_ownershipassessment_incidentevidence_and_more",
        )
    ]

    operations = [
        migrations.CreateModel(
            name="RemediationWorkflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("idempotency_key", models.CharField(max_length=128, unique=True)),
                ("correlation_id", models.CharField(max_length=128)),
                ("summary", models.CharField(max_length=1000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AWAITING_CONTRACT", "Awaiting contract"),
                            ("CONTRACT_LINKED", "Contract linked"),
                            ("DISPATCHED", "Dispatched"),
                            ("TIMED_OUT", "Timed out"),
                            ("CANCELLED", "Cancelled"),
                            ("VALIDATION_PENDING", "Validation pending"),
                            ("RETRY_REQUIRED", "Retry requires new contract"),
                            ("ESCALATED", "Escalated"),
                            ("RESUMED", "Workflow resumed"),
                        ],
                        max_length=32,
                    ),
                ),
                ("deadline_at", models.DateTimeField(blank=True, null=True)),
                ("timeline", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contract",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="projects.executioncontract",
                    ),
                ),
                (
                    "incident",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="remediation",
                        to="projects.failureincident",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="projects.project",
                    ),
                ),
                (
                    "run",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="projects.executionrun",
                    ),
                ),
                (
                    "scope",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="projects.executablescope",
                    ),
                ),
                (
                    "start_request",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="projects.executionstartrequest",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RemediationValidation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("validator_identity", models.CharField(max_length=255)),
                (
                    "outcome",
                    models.CharField(
                        choices=[("PASSED", "Passed"), ("FAILED", "Failed")],
                        max_length=16,
                    ),
                ),
                ("evidence_references", models.JSONField(default=list)),
                ("rationale", models.CharField(max_length=1000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "remediation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validation",
                        to="projects.remediationworkflow",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeploymentRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("DEPLOY", "Deploy"), ("ROLLBACK", "Rollback")],
                        max_length=16,
                    ),
                ),
                ("environment", models.CharField(max_length=64)),
                ("idempotency_key", models.CharField(max_length=128, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REQUESTED", "Requested"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        max_length=16,
                    ),
                ),
                ("provider_receipt", models.CharField(blank=True, max_length=255)),
                ("detail", models.CharField(blank=True, max_length=1000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approval",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="projects.governanceapproval",
                    ),
                ),
                (
                    "remediation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deployments",
                        to="projects.remediationworkflow",
                    ),
                ),
            ],
        ),
    ]
