# Generated by Django 5.2.14 on 2026-07-28 14:13

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0019_remediationworkflow_remediationvalidation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="remediationvalidation",
            name="execution_token",
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name="remediationworkflow",
            name="max_retries",
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name="remediationworkflow",
            name="retry_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="remediationvalidation",
            name="remediation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="validations",
                to="projects.remediationworkflow",
            ),
        ),
        migrations.AddConstraint(
            model_name="remediationvalidation",
            constraint=models.UniqueConstraint(
                fields=("remediation", "execution_token"),
                name="unique_remediation_validation_execution",
            ),
        ),
    ]
