# Generated by Django 5.2.14 on 2026-07-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0020_remediation_retry_validation_history"),
    ]

    operations = [
        migrations.AlterField(
            model_name="executionprovider",
            name="health_status",
            field=models.CharField(
                choices=[
                    ("UNKNOWN", "Unknown"),
                    ("CONFIGURED", "Configured"),
                    ("HEALTHY", "Healthy"),
                    ("DEGRADED", "Degraded"),
                    ("UNAVAILABLE", "Unavailable"),
                    ("MISCONFIGURED", "Misconfigured"),
                ],
                default="UNKNOWN",
                max_length=32,
            ),
        ),
    ]
