# Generated by Django 5.2.14 on 2026-07-29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("projects", "0022_akb_foundation")]

    operations = [
        migrations.CreateModel(
            name="EngineeringEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entity_key", models.CharField(max_length=160)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("APPLICATION", "Application"),
                            ("CAPABILITY", "Capability"),
                            ("FEATURE", "Feature"),
                            ("COMPONENT", "Component"),
                            ("SERVICE", "Service"),
                            ("API", "API"),
                            ("INTEGRATION", "Integration"),
                            ("ROADMAP_ITEM", "Roadmap item"),
                            ("CONSTITUTION_SECTION", "Constitution section"),
                            ("UI_PLAN", "UI plan"),
                            ("SYSTEM_DESIGN", "System design"),
                            ("ARCHITECTURE_DECISION", "Architecture decision"),
                            ("SPRINT", "Sprint"),
                            ("RELEASE", "Release"),
                            ("ENGINEERING_GATE", "Engineering gate"),
                            ("REMEDIATION", "Remediation"),
                            ("INCIDENT", "Incident"),
                            ("KNOWN_ISSUE", "Known issue"),
                            ("RUNBOOK", "Runbook"),
                        ],
                        max_length=32,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("state", models.CharField(default="CURRENT", max_length=32)),
                ("description", models.TextField(blank=True)),
                ("source_reference", models.CharField(max_length=255)),
                ("evidence_references", models.JSONField(default=list)),
                ("attributes", models.JSONField(default=dict)),
                ("approval_reference", models.CharField(blank=True, max_length=128)),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="engineering_entities",
                        to="projects.project",
                    ),
                ),
            ],
            options={"ordering": ["kind", "entity_key"]},
        ),
        migrations.CreateModel(
            name="EngineeringEntityRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("actor", models.CharField(max_length=128)),
                ("previous_version", models.PositiveIntegerField(default=0)),
                ("new_version", models.PositiveIntegerField()),
                ("source_reference", models.CharField(max_length=255)),
                ("approval_reference", models.CharField(blank=True, max_length=128)),
                ("reason", models.CharField(max_length=1000)),
                ("snapshot", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="projects.engineeringentity",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EngineeringRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("relationship_type", models.CharField(max_length=64)),
                ("work_reference", models.CharField(blank=True, max_length=255)),
                ("evidence_references", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="engineering_relationships",
                        to="projects.project",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_relationships",
                        to="projects.engineeringentity",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_relationships",
                        to="projects.engineeringentity",
                    ),
                ),
            ],
            options={"ordering": ["source_id", "relationship_type", "target_id"]},
        ),
        migrations.AddConstraint(
            model_name="engineeringentity",
            constraint=models.UniqueConstraint(
                fields=("project", "entity_key"), name="unique_engineering_entity_key"
            ),
        ),
        migrations.AddConstraint(
            model_name="engineeringentityrevision",
            constraint=models.UniqueConstraint(
                fields=("entity", "new_version"),
                name="unique_engineering_entity_revision_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="engineeringrelationship",
            constraint=models.UniqueConstraint(
                fields=("project", "source", "target", "relationship_type"),
                name="unique_engineering_relationship",
            ),
        ),
    ]
