# Generated by Django 5.2.14 on 2026-07-29 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0024_executionjob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="executablescope",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PROPOSED", "Proposed"),
                    ("APPROVED", "Approved"),
                    ("ACTIVE", "Active"),
                    ("COMPLETED", "Completed"),
                    ("RECONCILING", "Reconciling external execution"),
                    ("ACCEPTED", "Pass accepted"),
                    ("CANCELLED", "Cancelled"),
                    ("SUPERSEDED", "Superseded"),
                ],
                default="PROPOSED",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="ExternalExecutionReconciliation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RECONCILING", "Reconciling"),
                            ("PASS", "Pass"),
                            ("ACCEPTED", "Accepted"),
                        ],
                        max_length=16,
                    ),
                ),
                ("source_kind", models.CharField(max_length=32)),
                ("final_commit_sha", models.CharField(max_length=40)),
                ("evidence_manifest", models.JSONField(default=dict)),
                ("evidence_digest", models.CharField(max_length=64)),
                ("engineering_audit_path", models.CharField(max_length=255)),
                ("acceptance_evidence_path", models.CharField(max_length=255)),
                ("acceptance_reference", models.CharField(max_length=128)),
                ("transition_log", models.JSONField(default=list)),
                ("verification", models.JSONField(default=dict)),
                ("reconciled_by", models.CharField(max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scope",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="external_reconciliation",
                        to="projects.executablescope",
                    ),
                ),
            ],
        ),
    ]
