# Generated by Django 5.1.1 on 2026-07-29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("projects", "0027_technicalremediationloop")]

    operations = [
        migrations.AlterField(
            model_name="executionjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("QUEUED", "Queued"),
                    ("LEASED", "Leased"),
                    ("STARTED", "Started"),
                    ("RECOVERING", "Recovering"),
                    ("RECOVERY_REVIEW_REQUIRED", "Recovery review required"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                ],
                default="QUEUED",
                max_length=32,
            ),
        ),
    ]
