# Generated by Django 5.1.5 on 2026-07-29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0029_executionjob_rejected"),
    ]

    operations = [
        migrations.AddField(
            model_name="executionprogressevent",
            name="provider_event_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name="executionprogressevent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("provider_event_id__isnull", False)),
                fields=("run", "provider_event_id"),
                name="unique_execution_provider_event_identity",
            ),
        ),
    ]
