# Generated by Django 5.2.14 on 2026-07-29

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("projects", "0030_executionprogressevent_provider_event_identity")]

    operations = [
        migrations.CreateModel(
            name="ExecutionWorkspace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REQUESTED", "Requested"),
                            ("PROVISIONING", "Provisioning"),
                            ("READY", "Ready"),
                            ("IN_USE", "In use"),
                            ("VALIDATING", "Validating"),
                            ("RETAINED", "Retained"),
                            ("CLEANUP_PENDING", "Cleanup pending"),
                            ("CLEANED", "Cleaned"),
                            ("FAILED", "Failed"),
                        ],
                        default="REQUESTED",
                        max_length=32,
                    ),
                ),
                ("root_path", models.CharField(blank=True, max_length=1024)),
                ("repository_path", models.CharField(blank=True, max_length=1024)),
                ("repository_url", models.CharField(blank=True, max_length=512)),
                ("base_branch", models.CharField(blank=True, max_length=255)),
                ("base_commit_sha", models.CharField(blank=True, max_length=64)),
                ("base_ref", models.CharField(blank=True, max_length=255)),
                ("venv_path", models.CharField(blank=True, max_length=1024)),
                ("python_executable", models.CharField(blank=True, max_length=1024)),
                ("environment", models.JSONField(blank=True, default=dict)),
                ("database_profile", models.JSONField(blank=True, default=dict)),
                ("dependency_fingerprint", models.CharField(blank=True, max_length=64)),
                ("provider_pid", models.PositiveIntegerField(blank=True, null=True)),
                ("provisioned_at", models.DateTimeField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("retention_until", models.DateTimeField(blank=True, null=True)),
                ("cleanup_started_at", models.DateTimeField(blank=True, null=True)),
                ("cleaned_at", models.DateTimeField(blank=True, null=True)),
                ("failure_code", models.CharField(blank=True, max_length=128)),
                ("failure_details", models.JSONField(blank=True, default=dict)),
                ("cleanup_manifest", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workspace",
                        to="projects.executionrun",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
    ]
