# Generated by Django 5.2.14 on 2026-07-29 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0031_executionworkspace"),
    ]

    operations = [
        migrations.AddField(
            model_name="executionworkspace",
            name="migration_state",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="executionworkspace",
            name="runtime_profile",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="executionworkspace",
            name="runtime_services",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="executionworkspace",
            name="seed_state",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="RuntimeBootstrapProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("database", models.JSONField(blank=True, default=dict)),
                ("seed_command", models.JSONField(blank=True, default=list)),
                ("services", models.JSONField(blank=True, default=list)),
                ("environment", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runtime_bootstrap_profile",
                        to="projects.project",
                    ),
                ),
            ],
        ),
    ]
