# Generated by Django 5.2.14 on 2026-07-30

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("projects", "0032_executionworkspace_migration_state_and_more")]

    operations = [
        migrations.AlterField(
            model_name="executionrun",
            name="lifecycle",
            field=models.CharField(
                choices=[
                    ("REQUESTED", "Requested"),
                    ("STARTING", "Starting"),
                    ("RUNNING", "Running"),
                    ("CANCELLING", "Cancelling"),
                    ("VALIDATING", "Validating"),
                    ("REPAIRING", "Repairing"),
                    ("DOCUMENTING", "Documenting"),
                    ("CLOSING", "Closing"),
                    ("COMPLETED", "Completed"),
                    ("BLOCKED_BUSINESS_DECISION", "Blocked business"),
                    ("BLOCKED_EXTERNAL_INPUT", "Blocked external"),
                    ("FAILED_GOVERNANCE", "Failed governance"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="REQUESTED",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="ExecutionCancellation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("requested_by", models.CharField(max_length=255)),
                ("reason", models.CharField(max_length=1000)),
                (
                    "confirmation_reference",
                    models.CharField(blank=True, max_length=255, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CONFIRMATION_REQUIRED", "Confirmation required"),
                            ("CONFIRMED", "Confirmed"),
                            ("PROVIDER_CANCELLING", "Provider cancelling"),
                            ("CANCELLED", "Cancelled"),
                            ("ALREADY_TERMINAL", "Already terminal"),
                        ],
                        default="CONFIRMATION_REQUIRED",
                        max_length=32,
                    ),
                ),
                (
                    "provider_acknowledged_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cancellation",
                        to="projects.executionrun",
                    ),
                ),
            ],
        ),
    ]
