# Generated by Django 5.2.11 on 2026-07-31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0033_executioncancellation_executionrun_cancelling"),
    ]

    operations = [
        migrations.AddField(
            model_name="executionjob",
            name="lease_fencing_token",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
