# Generated by Codex for the governed Sprint 016 lifecycle retention policy.

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("projects", "0034_executionjob_lease_fencing_token")]

    operations = [
        migrations.AddField(
            model_name="executionworkspace",
            name="retention_reason",
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
