# Generated by Django 5.2.14 on 2026-07-31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("projects", "0035_executionworkspace_retention_reason")]

    operations = [
        migrations.AddField(
            model_name="conversationorchestration",
            name="orchestration_session",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="conversation_orchestration",
                to="projects.orchestrationsession",
            ),
        ),
        migrations.AddField(
            model_name="executioncontract",
            name="orchestration_decision_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="executioncontract",
            name="orchestration_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="execution_contracts",
                to="projects.orchestrationsession",
            ),
        ),
        migrations.AddField(
            model_name="executionrun",
            name="orchestration_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="execution_runs",
                to="projects.orchestrationsession",
            ),
        ),
        migrations.AddField(
            model_name="orchestrationsession",
            name="actor_identity",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="orchestrationsession",
            name="decision_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="orchestrationsession",
            name="execution_provider_id",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="orchestrationsession",
            name="final_outcome",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="orchestrationsession",
            name="runtime_profile_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="ownershipassessment",
            name="session",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ownership_assessment",
                to="projects.orchestrationsession",
            ),
        ),
        migrations.AlterField(
            model_name="ownershipassessment",
            name="incident",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ownership_assessment",
                to="projects.failureincident",
            ),
        ),
    ]
