# Generated by Django 5.2.14 on 2026-07-31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("projects", "0039_runtimedeployment")]

    operations = [
        migrations.AddField(
            model_name="conversationorchestration",
            name="caller_fingerprint",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="conversationorchestration",
            name="conversation_context",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name="McpConversationBinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("caller_fingerprint", models.CharField(max_length=64)),
                ("conversation_context", models.CharField(max_length=255)),
                ("proposal_version", models.PositiveIntegerField()),
                ("proposal_hash", models.CharField(max_length=64)),
                ("origin_tool", models.CharField(max_length=64)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scope",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mcp_conversation_bindings",
                        to="projects.executablescope",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["caller_fingerprint", "conversation_context"],
                        name="mcp_conversation_ctx_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("scope", "conversation_context"),
                        name="unique_mcp_scope_conversation_context",
                    )
                ],
            },
        ),
    ]
