# Generated by Django 5.2.14 on 2026-07-31 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0040_conversationorchestration_caller_fingerprint_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="technicalremediationloop",
            name="incident",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="technical_remediation_loop",
                to="projects.failureincident",
            ),
        ),
        migrations.AddField(
            model_name="technicalremediationloop",
            name="resume_checkpoint",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="TechnicalRemediationEscalation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=128, unique=True)),
                (
                    "classification",
                    models.CharField(
                        choices=[
                            (
                                "BUSINESS_DECISION_REQUIRED",
                                "Business decision required",
                            ),
                            ("TECHNICAL_REMEDIATION", "Technical remediation"),
                            (
                                "SECURITY_OR_GOVERNANCE_CONFLICT",
                                "Security or governance conflict",
                            ),
                            ("EXTERNAL_DEPENDENCY", "External dependency"),
                            ("NON_RECOVERABLE", "Non-recoverable"),
                        ],
                        max_length=40,
                    ),
                ),
                ("gate_name", models.CharField(max_length=128)),
                ("summary", models.CharField(max_length=1000)),
                ("evidence_references", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING_PRODUCT_OWNER", "Pending Product Owner")],
                        max_length=32,
                    ),
                ),
                ("timeline", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "incident",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="technical_escalation",
                        to="projects.failureincident",
                    ),
                ),
                (
                    "parent_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="technical_escalations",
                        to="projects.executionrun",
                    ),
                ),
                (
                    "parent_scope",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="technical_escalations",
                        to="projects.executablescope",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
    ]
