# Generated by Django 5.2.14 on 2026-07-31 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0041_sprint7_remediation_self_healing"),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalRemediationValidation',
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("validator_identity", models.CharField(max_length=255)),
                (
                    "outcome",
                    models.CharField(
                        choices=[("PASSED", "Passed"), ("FAILED", "Failed")],
                        max_length=16,
                    ),
                ),
                ("evidence_references", models.JSONField(default=list)),
                ("rationale", models.CharField(max_length=1000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "remediation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="independent_validations",
                        to="projects.technicalremediationloop",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
    ]
