# Generated by Django 5.2.14 on 2026-08-01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("projects", "0042_sprint7_independent_validation")]
    operations = [
        migrations.CreateModel(
            name="FactoryPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("questionnaire", models.JSONField(default=dict)),
                ("plan_hash", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_APPROVAL", "Pending plan approval"),
                            (
                                "BUSINESS_DECISION_REQUIRED",
                                "Business decision required",
                            ),
                            ("APPROVED", "Plan approved"),
                        ],
                        max_length=32,
                    ),
                ),
                ("business_escalation", models.TextField(blank=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approval",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="factory_plan_approval",
                        to="projects.governanceapproval",
                    ),
                ),
                (
                    "memory_candidate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="projects.knowledgeentry",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="factory_plans",
                        to="projects.project",
                    ),
                ),
                (
                    "roadmap_candidate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="projects.roadmapupdatecandidate",
                    ),
                ),
                (
                    "scope",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="factory_plan",
                        to="projects.executablescope",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        )
    ]
