# Generated by Django 5.2.16 on 2026-08-01

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("projects", "0043_factoryplan")]

    operations = [
        migrations.CreateModel(
            name="FactoryChatSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("actor_identity", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="factory_chat_sessions",
                        to="projects.project",
                    ),
                ),
            ],
            options={"ordering": ["-updated_at"]},
        ),
        migrations.CreateModel(
            name="FactoryChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("OWNER", "Product Owner"), ("ORKI", "Orki")],
                        max_length=16,
                    ),
                ),
                ("body", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("COMPLETED", "Completed"), ("FAILED", "Failed")],
                        default="COMPLETED",
                        max_length=16,
                    ),
                ),
                ("correlation_id", models.CharField(blank=True, max_length=128)),
                ("provider_id", models.CharField(blank=True, max_length=64)),
                ("model", models.CharField(blank=True, max_length=128)),
                ("prompt_hash", models.CharField(blank=True, max_length=64)),
                ("response_hash", models.CharField(blank=True, max_length=64)),
                ("latency_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("attempt_count", models.PositiveSmallIntegerField(default=1)),
                ("token_usage", models.JSONField(blank=True, default=dict)),
                ("error_code", models.CharField(blank=True, max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="projects.factorychatsession",
                    ),
                ),
            ],
            options={"ordering": ["created_at", "pk"]},
        ),
    ]
