# Generated by Django 5.1.11 on 2026-08-02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("projects", "0048_recommendation_engine_state")]

    operations = [
        migrations.AlterField(
            model_name="cognitivestateentry",
            name="kind",
            field=models.CharField(
                choices=[
                    ("MISSION", "Mission"),
                    ("BUSINESS_CONTEXT", "Business context"),
                    ("GOAL", "Goal"),
                    ("CONSTRAINT", "Constraint"),
                    ("FACT", "Fact"),
                    ("INFERENCE", "Inference"),
                    ("EVIDENCE", "Evidence"),
                    ("ASSUMPTION", "Assumption"),
                    ("RISK", "Risk"),
                    ("OPPORTUNITY", "Opportunity"),
                    ("RECOMMENDATION", "Recommendation"),
                    ("ALTERNATIVE", "Alternative"),
                    ("TRADE_OFF", "Trade-off"),
                    ("OPEN_DECISION", "Open decision"),
                    ("ACCEPTED_DECISION", "Accepted decision"),
                ],
                max_length=32,
            ),
        )
    ]
