# Generated by Django 5.1.6 on 2026-08-07

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("projects", "0054_operational_reasoning_engine_state")]

    operations = [
        migrations.CreateModel(
            name="OrkiGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("intent_reference", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("ACHIEVED", "Achieved"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="OPEN",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cognitive_goal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runtime_goal_references",
                        to="projects.cognitivestateentry",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orki_goals",
                        to="projects.project",
                    ),
                ),
                (
                    "source_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runtime_goals",
                        to="projects.factorychatsession",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="OrkiPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("plan_hash", models.CharField(blank=True, max_length=64)),
                ("strategy_references", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SELECTED", "Selected"),
                            ("SUPERSEDED", "Superseded"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cognitive_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runtime_plan_references",
                        to="projects.cognitivestateentry",
                    ),
                ),
                (
                    "factory_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runtime_plans",
                        to="projects.factoryplan",
                    ),
                ),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plans",
                        to="projects.orkigoal",
                    ),
                ),
            ],
            options={"ordering": ["goal", "-version"]},
        ),
        migrations.CreateModel(
            name="OrkiExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("SHADOW", "Shadow"), ("LIVE", "Live")],
                        default="SHADOW",
                        max_length=16,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("PLANNING", "Planning"),
                            ("WAITING_APPROVAL", "Waiting for approval"),
                            ("WAITING_GOVERNANCE", "Waiting for governance"),
                            ("DISPATCHING", "Dispatching"),
                            ("RUNNING", "Running"),
                            ("WAITING_EXTERNAL", "Waiting for external input"),
                            ("PAUSED", "Paused"),
                            ("SUCCEEDED", "Succeeded"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="CREATED",
                        max_length=24,
                    ),
                ),
                ("state_version", models.PositiveIntegerField(default=0)),
                ("paused_from_state", models.CharField(blank=True, max_length=24)),
                ("waiting_reason", models.JSONField(blank=True, default=dict)),
                ("governance_reference", models.JSONField(blank=True, default=dict)),
                ("provider_context", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "execution_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orki_executions",
                        to="projects.executionrun",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="executions",
                        to="projects.orkiplan",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="OrkiRuntimeEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.PositiveIntegerField()),
                ("event_type", models.CharField(max_length=64)),
                ("actor_identity", models.CharField(blank=True, max_length=255)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("evidence_references", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="projects.orkiexecution",
                    ),
                ),
            ],
            options={"ordering": ["execution", "sequence"]},
        ),
        migrations.AddConstraint(
            model_name="orkiplan",
            constraint=models.UniqueConstraint(
                fields=("goal", "version"), name="unique_orki_plan_goal_version"
            ),
        ),
        migrations.AddIndex(
            model_name="orkiexecution",
            index=models.Index(
                fields=["state", "mode", "created_at"],
                name="projects_or_state_ba1e6f_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="orkiruntimeevent",
            constraint=models.UniqueConstraint(
                fields=("execution", "sequence"), name="unique_orki_runtime_sequence"
            ),
        ),
    ]
