# Generated by Django 5.1.6 on 2026-08-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0055_orki_runtime_foundation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orkiexecution",
            name="state",
            field=models.CharField(
                choices=[
                    ("CREATED", "Created"),
                    ("PLANNING", "Planning"),
                    ("WAITING_APPROVAL", "Waiting for approval"),
                    ("WAITING_GOVERNANCE", "Waiting for governance"),
                    ("DISPATCHING", "Dispatching"),
                    ("RUNNING", "Running"),
                    ("WAITING_EXTERNAL", "Waiting for external input"),
                    ("WAITING_FOR_USER", "Waiting for user"),
                    ("PAUSED", "Paused"),
                    ("SUCCEEDED", "Succeeded"),
                    ("FAILED", "Failed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="CREATED",
                max_length=24,
            ),
        ),
    ]
