# Generated by Django 5.1.6 on 2026-08-08
# ruff: noqa: E501

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("projects", "0056_orkiexecution_waiting_for_user")]

    operations = [
        migrations.AlterField(
            model_name="orkiexecution", name="state",
            field=models.CharField(
                max_length=24, default="CREATED",
                choices=[("CREATED", "Created"), ("PLANNING", "Planning"),
                    ("WAITING_APPROVAL", "Waiting for approval"), ("WAITING_GOVERNANCE", "Waiting for governance"),
                    ("DISPATCHING", "Dispatching"), ("RUNNING", "Running"), ("VERIFYING", "Verifying"),
                    ("REFLECTING", "Reflecting"), ("KNOWLEDGE_INTEGRATING", "Knowledge integrating"),
                    ("WAITING_EXTERNAL", "Waiting for external input"), ("WAITING_FOR_USER", "Waiting for user"),
                    ("PAUSED", "Paused"), ("SUCCEEDED", "Succeeded"), ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"), ("CANCELLED", "Cancelled")],
            ),
        ),
        migrations.CreateModel(
            name="OrkiReflection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("analysis", models.JSONField(blank=True, default=dict)),
                ("evidence_references", models.JSONField(blank=True, default=list)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("execution", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="reflection", to="projects.orkiexecution")),
            ],
        ),
        migrations.CreateModel(
            name="OrkiKnowledgeIntegration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("NOT_REQUIRED", "Not required"), ("CANDIDATE_CREATED", "Candidate created"), ("ACCEPTED_FOR_REVIEW", "Accepted for governance review"), ("REJECTED", "Rejected")], default="NOT_REQUIRED", max_length=32)),
                ("evidence_references", models.JSONField(blank=True, default=list)),
                ("embedding_reference", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)),
                ("knowledge_entry", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="runtime_integrations", to="projects.knowledgeentry")),
                ("reflection", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="knowledge_integration", to="projects.orkireflection")),
            ],
        ),
    ]
