# Generated by Django 5.2.12 on 2026-08-09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0064_repository_knowledge_receipt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="factorymission",
            name="phase",
            field=models.CharField(
                choices=[
                    ("DISCOVERY", "Discovery"),
                    ("QUESTION_REQUIRED", "Question required"),
                    ("REQUIREMENTS_SUFFICIENT", "Requirements sufficient"),
                    ("PLAN_READY", "Plan ready"),
                    ("AWAITING_PRODUCT_OWNER_APPROVAL", "Awaiting approval"),
                    ("PLAN_APPROVED", "Plan approved"),
                    ("ORKI_OWNS_DELIVERY", "Orki owns delivery"),
                    ("IMPLEMENTING", "Implementing"),
                    ("VALIDATING", "Validating"),
                    ("DELIVERED", "Delivered"),
                    (
                        "AWAITING_PRODUCT_OWNER_ACCEPTANCE",
                        "Awaiting acceptance",
                    ),
                    ("ACCEPTED", "Accepted"),
                ],
                default="DISCOVERY",
                max_length=48,
            ),
        ),
        migrations.AlterField(
            model_name="orkiexecution",
            name="state",
            field=models.CharField(
                choices=[
                    ("CREATED", "Created"),
                    ("UNDERSTANDING", "Mission understanding"),
                    ("SEMANTIC_SEARCH", "Semantic search"),
                    ("GAP_ANALYSIS", "Gap analysis"),
                    ("QUESTION_GENERATION", "Question generation"),
                    ("WAITING_USER", "Waiting for user"),
                    ("PLANNING", "Planning"),
                    ("READY", "Ready"),
                    ("WAITING", "Waiting"),
                    ("RETRYING", "Retrying"),
                    ("RECOVERY", "Recovery"),
                    ("WAITING_APPROVAL", "Waiting for approval"),
                    ("WAITING_GOVERNANCE", "Waiting for governance"),
                    ("DISPATCHING", "Dispatching"),
                    ("RUNNING", "Running"),
                    ("VERIFYING", "Verifying"),
                    ("REFLECTING", "Reflecting"),
                    ("KNOWLEDGE_INTEGRATING", "Knowledge integrating"),
                    ("KNOWLEDGE_CANDIDATE", "Knowledge candidate"),
                    ("WAITING_EXTERNAL", "Waiting for external input"),
                    ("WAITING_FOR_USER", "Waiting for user"),
                    ("PAUSED", "Paused"),
                    ("SUCCEEDED", "Succeeded"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="CREATED",
                max_length=24,
            ),
        ),
    ]
