# Generated by Django 5.2.14 on 2026-08-09 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0065_orki_question_gate"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("workflow_key", models.CharField(max_length=128)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("READY", "Ready"),
                            ("RUNNING_STEP", "Running step"),
                            ("WAITING", "Waiting"),
                            ("RETRY", "Retry"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="CREATED",
                        max_length=24,
                    ),
                ),
                ("state_version", models.PositiveIntegerField(default=0)),
                ("input_data", models.JSONField(blank=True, default=dict)),
                ("output_data", models.JSONField(blank=True, default=dict)),
                ("selection_evidence", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mission_execution",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workflow_instance",
                        to="projects.orkiexecution",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkflowCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("definition", models.JSONField(default=dict)),
                ("evidence_references", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("GENERATED", "Generated"),
                            ("IN_REVIEW", "In review"),
                            ("APPROVED", "Approved"),
                            ("EMBEDDED", "Embedded"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="GENERATED",
                        max_length=16,
                    ),
                ),
                ("approval_reference", models.CharField(blank=True, max_length=255)),
                ("embedding_reference", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reflection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workflow_candidates",
                        to="projects.orkireflection",
                    ),
                ),
                (
                    "workflow",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="candidate",
                        to="projects.workflowinstance",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkflowStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step_key", models.CharField(max_length=128)),
                ("sequence", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("WAITING", "Waiting"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("dependencies", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="steps",
                        to="projects.workflowinstance",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_key", models.CharField(max_length=128)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("AI", "AI"),
                            ("TOOL", "Tool"),
                            ("HUMAN", "Human"),
                            ("WORKFLOW", "Workflow"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("WAITING", "Waiting"),
                            ("RETRY", "Retry"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("input_data", models.JSONField(blank=True, default=dict)),
                ("output_data", models.JSONField(blank=True, default=dict)),
                ("evidence_references", models.JSONField(blank=True, default=list)),
                ("retry_count", models.PositiveIntegerField(default=0)),
                ("max_retries", models.PositiveIntegerField(default=2)),
                ("timeout_seconds", models.PositiveIntegerField(default=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "execution_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workflow_tasks",
                        to="projects.executionrun",
                    ),
                ),
                (
                    "workflow_step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tasks",
                        to="projects.workflowstep",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkflowTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("workflow_key", models.CharField(max_length=128)),
                ("version", models.PositiveIntegerField(default=1)),
                ("definition", models.JSONField(default=dict)),
                ("definition_hash", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CANDIDATE", "Candidate"),
                            ("IN_REVIEW", "In review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("RETIRED", "Retired"),
                        ],
                        default="CANDIDATE",
                        max_length=16,
                    ),
                ),
                ("approval_reference", models.CharField(blank=True, max_length=255)),
                ("embedding_reference", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workflow_templates",
                        to="projects.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkflowSelectionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.TextField()),
                ("candidates", models.JSONField(blank=True, default=list)),
                ("reasoning", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "workflow",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="selection_record",
                        to="projects.workflowinstance",
                    ),
                ),
                (
                    "selected_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="selection_records",
                        to="projects.workflowtemplate",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="workflowinstance",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="instances",
                to="projects.workflowtemplate",
            ),
        ),
        migrations.CreateModel(
            name="WorkflowEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.PositiveIntegerField()),
                ("event_type", models.CharField(max_length=64)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="projects.workflowinstance",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("workflow", "sequence"),
                        name="unique_workflow_event_sequence",
                    )
                ]
            },
        ),
        migrations.AddConstraint(
            model_name="workflowstep",
            constraint=models.UniqueConstraint(
                fields=("workflow", "step_key"), name="unique_workflow_step_key"
            ),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.UniqueConstraint(
                fields=("workflow_step", "task_key"), name="unique_workflow_task_key"
            ),
        ),
        migrations.AddConstraint(
            model_name="workflowtemplate",
            constraint=models.UniqueConstraint(
                fields=("project", "workflow_key", "version"),
                name="unique_workflow_template_version",
            ),
        ),
    ]
